services:
  - type: web
    name: geekify-backend
    env: dotnet
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/YourProjectName.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT